default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dima
  password: 1
  host: localhost

development:
  <<: *default
  database: app_dev

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_prod